JaeYeopHan/Interview_Question_for_Beginner

Java/README.md
=> 컬렉션 내용 추가 (#12)

Algorithm/README.md
알고리즘 연습 사이트인 프로젝트 오일러를 추가했습니다.
=> 알고리즘 연습 사이트 추가

Algorithm/README.md
제가 가장 좋아하는 코딩 연습 사이트 하나 추가했습니다.
Gamification 이 매우 잘되있습니다.
=> 알고리즘 문제 연습 사이트 하나 추가

Development_common_sense/README.md
RESTful API 부분에 오탈자가 있어서 수정하였습니다. 😃
=>  Edit typos 

Python/README.md
=> Fix minor typo

README.md
페이스북 개발자인 [Yangshun Tay](https://github.com/yangshun)의 FE 인터뷰 핸드북 한국어 번역입니다
Yangshun Tay의 주관적인 견해과 경험이 일부 담겨있어 신입부터 경력 FE 개발자까지 모두 참고하기 좋은 자료입니다
=> Add:  Front-End > 추가자료 > Front-end Interview Handbook

README.md
찾아보니 thedavddias의 Front-End-Checklist는 한국어로 번역된 repository가 있습니다.
링크 수정 해서 pull request 합니다. 
항상 감사드립니다. :)
=> Edit Front-end Checklist links

Development_common_sense/README.md
리스코프 치환 원칙 영문 표기가 'Likov'가 되어있던걸 'Liskov'로 수정했습니다.
=> 개발 상식 오타 수정

JavaScript/README.md
=> javascript의 async/await에 대해 자료를 추가했습니다.

Algorithm/README.md
'어떻게 정할하면 정확히' -> '어떻게 정하면 정확히' 로 수정했습니다.
=> 알고리즘 오타 수정

iOS/README.md
* ARC 내용 추가
* 자동 참조 계수 내용 추가
* 자동 참조 계수 해결 방법(weak, unowned) 내용 추가
=> [New Resource] iOS Memory Management 추가

README.md
* python 추가 자료 링크 주소가 변경되어 수정했습니다.
=> Python 추가 자료 link 수정

JavaScript/README.md
* promise, async/await 비교 예제 추가
* .catch, try-catch 추가
* NPE 체크 소스 추가
* const, arrow => async function()
=> promise와 async/await 구현 비교 예시 추가

Algorithm/README.md
- 오탈자로 보이는 comma 제거합니다.
- 알고리즘 문제 연습 사이트 추가합니다.
(say something...)
=> /modify-README.md

JavaScript/README.md
(say something...)
resloved: #89
=> Javascript Arrow Function 설명 및 예제코드 추가합니다.

README.md
🔧Fix: broken link
[https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/master/Translations/Korean](https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/master/Translations/Korean)
to
[https://h5bp.org/Front-end-Developer-Interview-Questions/translations/korean/](https://h5bp.org/Front-end-Developer-Interview-Questions/translations/korean/)
=> 🔧Fix: broken link

DataStructure/README.md
DataStructure 문서에서 이동하지 않은 anchor link를 수정했습니다.
=> fix broken anchor in DataStructure

JavaScript/README.md
안녕하세요! JS의 this 문단에서 빠진 부분을 찾았습니다 :D
=> fix: 메서드 자신은 this의 출력 결과에 포함됩니다

Python/README.md, README.md
kakao 면접 중 받은 'python 내부의 sort는 무엇으로 구현되어있는가'
질문에 대한 내용을 추가하였습니다.
=> Update 'timsort' to python chapter

Development_common_sense/README.md
=> Git 과 GitHub 에 대해서 링크 버그 수정

README.md
목차에 연결되어 있는 링크 `What is this?` 부분의 해시 값을 수정하였습니다.
=> 목차에 잘못 연결된 링크를 수정했습니다.

Java/README.md
* Collections 함수명 오타 수정 
* synchroziedList() -> synchronizedList()
* synchroziedSet() -> synchronizedSet()
* synchroziedMap() -> synchronizedMap()
=> fix: Java 동기화(Synchronized) 부분 오타 수정

Development_common_sense/README.md, OS/README.md
REpresentational -> Representational 수정했습니다.
=> Edit typos

JavaScript/README.md
=> fix: this에 대하여 상황2 설명 오타 수정

DataStructure/README.md
=> 자료 구조 오타 수정

OS/README.en.md
I realize that there is no current work to translate this directory into English. I think it would be nice to have an English version.
I will translate the repo to English, but I can't be completely sure of the content. If possible, please review it.
I will put the translation in a file "README.en.md" to the same directory with the original version.
=> [English] OS

OS/README.md
안녕하세요. 좋은 자료 잘 보고 있습니다. 덕분에 수월하게 공부하고 있습니다. 감사합니다.
관련된 내용을 공부하다가 보고 있는 책의 내용과 다른 점이 있어서 pull request를 보냅니다. 내용은 아래와 같습니다.
lock에 대한 내용 가운데 하드웨어 기반 해결책이라는 내용이 있는데 해당 기법은 comapre_and_swap이라는 어셈블리 명령어라고 합니다. 적혀 있는 내용은 소프트웨어 기반 내용이라서 해당 내용을 삭제하였습니다. 또한 Lock이라는 제목도 좋지만 운영체제를 공부하는
분들에게 익숙한 Mutex Lock이라는 용어를 사용하면 더 이해하기 쉬울 것 같아서 수정을 하였습니다.
해당 내용은 [Operating System Concept 10 edition](http://www.yes24.com/Product/Goods/89496122)의 296p ~ 297p를 참고하였습니다.
=> Inaccurate information : mutex lock 내용 수정

README.md
원작자 분이 링크를 수정하셔서 기존 링크 들어가면 404 뜹니다.
기존 리포지토리 들어가보면 외부 사이트로 링크를 옮기셔서, 아예 그 링크로 변경하는 게 좋을 것 같습니다!
=> frontendinterviewhandbook 링크 수정

Python/README.md
=> fine grained lock 링크 에러 수정

Java/README.md
Java Synchronized 키워드에 대해 자세히 적어봤습니다. synchronized 범위 대해서 알고있고 이를 적절하게 조절하여 사용하는 방법도 추가하면 어떨까라는 생각에 PR 올렸습니다. 
감사합니다!
=> Java synchronized에 대한 이론 설명 보충

JavaScript/README.md
=> Added details related to critical rendering path

FrontEnd/README.md
- Frontend
- Document Object Model
- Reference
404로 redirect되는 Reference 링크를 수정했습니다
=> fix: "Document Object Model Event" Reference link 수정

FrontEnd/README.md, JavaScript/README.md
1. Critical Rendering Path 목차 추가
2. Critical Rendering Path 위치 변경
3. Critical Rendering Path 간단한 설명 추가
=> Critical Rendering Path 관련 수정
